---
- hosts:
    - postgresql
  remote_user: admin
  become: yes
  roles:
    - postgresql
  vars:
    ansible_ssh_private_key_file: "{{ node_ssh_admin_private_key_path | default('~/.ssh/admin/id_ed25519') }}"
